{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "nfc-reader",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "nfc-reader-2.6.1.aar",
          "url": "nfc-reader-2.6.1.aar",
          "size": 495542,
          "sha512": "394ed857ccffb58be182af2e8b9f36626dad908251ac76601bc5499f6e530df91e4b25fdab601c3cd683eb2b78b51116c8f427a705e614a200b797aa72f2ee8f",
          "sha256": "d916d32ee260678d4f3ffae46dbe64a58164a152699ddd19b8d34e80d391fbd6",
          "sha1": "1a2fec1ea6a4e8c718f130e3996dfd61999720be",
          "md5": "d0a39b5f11808358f55e13f12d22882f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.7.18"
          }
        },
        {
          "group": "com.github.Tgo1014",
          "module": "JP2ForAndroid",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-android",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.mhshams",
          "module": "jnbis",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.sf.scuba",
          "module": "scuba-sc-android",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "org.ejbca.cvc",
          "module": "cert-cvc",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "com.madgag.spongycastle",
          "module": "prov",
          "version": {
            "requires": "1.58.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "nfc-reader-2.6.1.aar",
          "url": "nfc-reader-2.6.1.aar",
          "size": 495542,
          "sha512": "394ed857ccffb58be182af2e8b9f36626dad908251ac76601bc5499f6e530df91e4b25fdab601c3cd683eb2b78b51116c8f427a705e614a200b797aa72f2ee8f",
          "sha256": "d916d32ee260678d4f3ffae46dbe64a58164a152699ddd19b8d34e80d391fbd6",
          "sha1": "1a2fec1ea6a4e8c718f130e3996dfd61999720be",
          "md5": "d0a39b5f11808358f55e13f12d22882f"
        }
      ]
    }
  ]
}
