{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "recorder",
    "version": "2.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.7.aar",
          "url": "recorder-2.6.7.aar",
          "size": 71937,
          "sha512": "dc60bdab21ea3186bd191a6ecce9549048f83c10e821df109724a5dd58898c60ea318022d21065d96b52f3838ae46ae505d5217c894a5cc278534571825fa4af",
          "sha256": "69856ed3a58e93cb5da46c2544657959c03e926110208a9afb7a6581ff48519d",
          "sha1": "acd6d0a533293e6cfcff1f94d67864af46fec800",
          "md5": "f3d6553a40cbe063fe59fb3979d54790"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.78"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.7.aar",
          "url": "recorder-2.6.7.aar",
          "size": 71937,
          "sha512": "dc60bdab21ea3186bd191a6ecce9549048f83c10e821df109724a5dd58898c60ea318022d21065d96b52f3838ae46ae505d5217c894a5cc278534571825fa4af",
          "sha256": "69856ed3a58e93cb5da46c2544657959c03e926110208a9afb7a6581ff48519d",
          "sha1": "acd6d0a533293e6cfcff1f94d67864af46fec800",
          "md5": "f3d6553a40cbe063fe59fb3979d54790"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "recorder-2.6.7-sources.jar",
          "url": "recorder-2.6.7-sources.jar",
          "size": 30281,
          "sha512": "d9651980a8fd47d90d0e623de08aed916bf221d338965db9bd7ffdc272c2ea0e9800e08d11cf74cf5ecb4b4ceccd8e35df0e7237543217eb5fb9a749bef916ef",
          "sha256": "bc17a3dfa2a000329f8ef3100c6b539e7ac3f9f18d1e86a6d7caa811248411d4",
          "sha1": "47456230919258e7d7f5eaab74a4c0a68fff81b1",
          "md5": "788f57a2d5f6018a63d1e6040910f2d9"
        }
      ]
    }
  ]
}
