{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "sdk",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.5.7.aar",
          "url": "sdk-2.5.7.aar",
          "size": 1664603,
          "sha512": "5f8a8f6617221c3e466b611e332ced013c93890e7bdd52e751522b0d2a22e5407228980d59662c654f6bf76753517240204cc24e8fa4e3110751c195cc29a5a7",
          "sha256": "03b889435af7bc8dccf41262b352bfc37c0b6e0cc0f1d7f7b12f8b48c5c24a72",
          "sha1": "9b516308c337bca3a3950a150911ab6bede933a7",
          "md5": "a1fa56ffb5d1f3b34a89396865b43498"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.6.86"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.intuit.sdp",
          "module": "sdp-android",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-mlkit-text-recognition",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha28"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.7.18"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-android",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.Tgo1014",
          "module": "JP2ForAndroid",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "cz.adaptech.android",
          "module": "tesseract4android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.mhshams",
          "module": "jnbis",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.sf.scuba",
          "module": "scuba-sc-android",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "org.ejbca.cvc",
          "module": "cert-cvc",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "com.madgag.spongycastle",
          "module": "prov",
          "version": {
            "requires": "1.58.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.5.7.aar",
          "url": "sdk-2.5.7.aar",
          "size": 1664603,
          "sha512": "5f8a8f6617221c3e466b611e332ced013c93890e7bdd52e751522b0d2a22e5407228980d59662c654f6bf76753517240204cc24e8fa4e3110751c195cc29a5a7",
          "sha256": "03b889435af7bc8dccf41262b352bfc37c0b6e0cc0f1d7f7b12f8b48c5c24a72",
          "sha1": "9b516308c337bca3a3950a150911ab6bede933a7",
          "md5": "a1fa56ffb5d1f3b34a89396865b43498"
        }
      ]
    }
  ]
}
