{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "nfc-reader",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "nfc-reader-3.3.0.aar",
          "url": "nfc-reader-3.3.0.aar",
          "size": 590073,
          "sha512": "39cd38aad8ba0ffd9d14078d3fbbdc50ec97dba00493e3d6cde17f90accb3902cb06a39c27d0173348e7138b4025b11b5242df37789321d70a3c146b0d2f9195",
          "sha256": "8d3145b7e6804095b88d5d5e9df0df5f9fdea179373bd1ce3ba21f0a92434f93",
          "sha1": "bad45075beae5791e3dc2d324cce1ea51e18ff3b",
          "md5": "e705b62b3d8a54d42b41871ffce1f9ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.7"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.6.7"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.7.18"
          }
        },
        {
          "group": "dev.keiji.jp2",
          "module": "jp2-android",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-android",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.github.mhshams",
          "module": "jnbis",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.sf.scuba",
          "module": "scuba-sc-android",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "org.ejbca.cvc",
          "module": "cert-cvc",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "com.madgag.spongycastle",
          "module": "prov",
          "version": {
            "requires": "1.58.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "nfc-reader-3.3.0.aar",
          "url": "nfc-reader-3.3.0.aar",
          "size": 590073,
          "sha512": "39cd38aad8ba0ffd9d14078d3fbbdc50ec97dba00493e3d6cde17f90accb3902cb06a39c27d0173348e7138b4025b11b5242df37789321d70a3c146b0d2f9195",
          "sha256": "8d3145b7e6804095b88d5d5e9df0df5f9fdea179373bd1ce3ba21f0a92434f93",
          "sha1": "bad45075beae5791e3dc2d324cce1ea51e18ff3b",
          "md5": "e705b62b3d8a54d42b41871ffce1f9ff"
        }
      ]
    }
  ]
}
