{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "sdk",
    "version": "1.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sdk-1.8.9.aar",
          "url": "sdk-1.8.9.aar",
          "size": 1551824,
          "sha512": "92706d5041de0477b5e328913a97c0e28524e4bf0af4cdb8a7afb560b8ab3b5417aa4c18f4c6dad180d200cf9e807a793084a8db42c6445ce1de6033e1681a94",
          "sha256": "6927392c1d0469e33103ef2798df4050d9a14d2416b2bf3d204ec48970621cf2",
          "sha1": "4b2ed7e099e2997ce3750ceff5751c250596fc96",
          "md5": "4a264baa7049b37250508c7a280320ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.4.5"
          }
        },
        {
          "group": "com.intuit.sdp",
          "module": "sdp-android",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-mlkit-text-recognition",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha28"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.7.18"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-android",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "cz.adaptech.android",
          "module": "tesseract4android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.mhshams",
          "module": "jnbis",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.sf.scuba",
          "module": "scuba-sc-android",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "org.ejbca.cvc",
          "module": "cert-cvc",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "com.madgag.spongycastle",
          "module": "prov",
          "version": {
            "requires": "1.58.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.8.9.aar",
          "url": "sdk-1.8.9.aar",
          "size": 1551824,
          "sha512": "92706d5041de0477b5e328913a97c0e28524e4bf0af4cdb8a7afb560b8ab3b5417aa4c18f4c6dad180d200cf9e807a793084a8db42c6445ce1de6033e1681a94",
          "sha256": "6927392c1d0469e33103ef2798df4050d9a14d2416b2bf3d204ec48970621cf2",
          "sha1": "4b2ed7e099e2997ce3750ceff5751c250596fc96",
          "md5": "4a264baa7049b37250508c7a280320ce"
        }
      ]
    }
  ]
}
