{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "screen-recorder",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "screen-recorder-3.4.1.aar",
          "url": "screen-recorder-3.4.1.aar",
          "size": 70890,
          "sha512": "325d0b56e3c41b3f84bac11bd441a1105d6df9247cc5199a1924a9d21a6285432ce5ff58a6f5be15c4cfb96d544439801efe6da7a863074f8adf488d5bcc4c57",
          "sha256": "bb0afbdbee6f0f4026a502957b1e96326c14dceeec037f8f06f86c6ccac218a9",
          "sha1": "7972559e8cadb2489b0297de64fb0535dd087fd1",
          "md5": "6b809b5e5d65f04438a710170727d87a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "screen-recorder-3.4.1.aar",
          "url": "screen-recorder-3.4.1.aar",
          "size": 70890,
          "sha512": "325d0b56e3c41b3f84bac11bd441a1105d6df9247cc5199a1924a9d21a6285432ce5ff58a6f5be15c4cfb96d544439801efe6da7a863074f8adf488d5bcc4c57",
          "sha256": "bb0afbdbee6f0f4026a502957b1e96326c14dceeec037f8f06f86c6ccac218a9",
          "sha1": "7972559e8cadb2489b0297de64fb0535dd087fd1",
          "md5": "6b809b5e5d65f04438a710170727d87a"
        }
      ]
    }
  ]
}
