{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "sdk",
    "version": "1.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lbubu2ztz5fg5jrc2omi6chhae"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sdk-1.6.5.aar",
          "url": "sdk-1.6.5.aar",
          "size": 1347456,
          "sha512": "ce0f0c7bbe107cb6ddb13e5a7a463867c536c232ff87714cead1a108a1413ceb1d4b2fdeb94a7ea4feac082fd4427cacdc48bbc4a99e15fb51aedcf7cb4509ce",
          "sha256": "f534ad2d563a76cedb6cdf0b7f5c8984bd047912e70c7be97640d16632423a36",
          "sha1": "950f630b551f4d61c9c55087adbc4b0da2877f56",
          "md5": "cebb919477be4c07b61c02554063fb6f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-viewmodel",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.6.5.aar",
          "url": "sdk-1.6.5.aar",
          "size": 1347456,
          "sha512": "ce0f0c7bbe107cb6ddb13e5a7a463867c536c232ff87714cead1a108a1413ceb1d4b2fdeb94a7ea4feac082fd4427cacdc48bbc4a99e15fb51aedcf7cb4509ce",
          "sha256": "f534ad2d563a76cedb6cdf0b7f5c8984bd047912e70c7be97640d16632423a36",
          "sha1": "950f630b551f4d61c9c55087adbc4b0da2877f56",
          "md5": "cebb919477be4c07b61c02554063fb6f"
        }
      ]
    }
  ]
}
