{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facetec",
    "module": "sdk",
    "version": "9.6.66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sdk-9.6.66.aar",
          "url": "sdk-9.6.66.aar",
          "size": 1514,
          "sha512": "d7c5ec85c074986cbb27852b32c8e39b654842bdca3e40a1dc41ef308b8b3e36ea270b691442ca7db5c684845b5da910a689d09f6c613f849ed0fcdea2501427",
          "sha256": "c3ec846eb8494e5bb6ed1d31a94e380412c92c16a49ac189c98a1962a42ea885",
          "sha1": "ee9387a587a49a616dd210048bf84130c8037fe9",
          "md5": "ad97fd247c439c3f0f176c7750bf3115"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-9.6.66.aar",
          "url": "sdk-9.6.66.aar",
          "size": 1514,
          "sha512": "d7c5ec85c074986cbb27852b32c8e39b654842bdca3e40a1dc41ef308b8b3e36ea270b691442ca7db5c684845b5da910a689d09f6c613f849ed0fcdea2501427",
          "sha256": "c3ec846eb8494e5bb6ed1d31a94e380412c92c16a49ac189c98a1962a42ea885",
          "sha1": "ee9387a587a49a616dd210048bf84130c8037fe9",
          "md5": "ad97fd247c439c3f0f176c7750bf3115"
        }
      ]
    }
  ]
}
