{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "document-autoresolver",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "document-autoresolver-3.5.0.aar",
          "url": "document-autoresolver-3.5.0.aar",
          "size": 819717,
          "sha512": "245f86f98792666a37fb3f0509d60ea69db3d8f0cafa50694a18ee9dafd7bb642d372205188d176f18ebc4a1ba3fc43f87a7190bbe3ee747dd3627cef9c48eb9",
          "sha256": "2cd1834d766a359d03219010fe92f1a54127194932b598096e5004bb8e28e499",
          "sha1": "2da57e067a1bc48a696ae2f6ee4140576fb34405",
          "md5": "e26efd6edf0b1996ddf4e21629cf095f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-support",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu-api",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.kyc.ondato",
          "module": "sdk-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "document-autoresolver-3.5.0.aar",
          "url": "document-autoresolver-3.5.0.aar",
          "size": 819717,
          "sha512": "245f86f98792666a37fb3f0509d60ea69db3d8f0cafa50694a18ee9dafd7bb642d372205188d176f18ebc4a1ba3fc43f87a7190bbe3ee747dd3627cef9c48eb9",
          "sha256": "2cd1834d766a359d03219010fe92f1a54127194932b598096e5004bb8e28e499",
          "sha1": "2da57e067a1bc48a696ae2f6ee4140576fb34405",
          "md5": "e26efd6edf0b1996ddf4e21629cf095f"
        }
      ]
    }
  ]
}
