{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "screen-recorder",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "screen-recorder-3.3.0.aar",
          "url": "screen-recorder-3.3.0.aar",
          "size": 70881,
          "sha512": "4bffbbb289022ad6faa5e8a94eaf09b4bdcac1ab5655c35b5ee7fca3f985e128de4ad7b2a9d5f4fb4f75132ac80acd4a14883bdf34eea3b82f3993ad9278b7e4",
          "sha256": "bbb6c4dfeb1425c24c7b446d65e69e28e501f3a59db1632fad3e2d8bb1f9a9f1",
          "sha1": "96fd89fe860c6dcbc164f3d722ed3d816779ca64",
          "md5": "12f205974710134416cdfacc1d2f99e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "screen-recorder-3.3.0.aar",
          "url": "screen-recorder-3.3.0.aar",
          "size": 70881,
          "sha512": "4bffbbb289022ad6faa5e8a94eaf09b4bdcac1ab5655c35b5ee7fca3f985e128de4ad7b2a9d5f4fb4f75132ac80acd4a14883bdf34eea3b82f3993ad9278b7e4",
          "sha256": "bbb6c4dfeb1425c24c7b446d65e69e28e501f3a59db1632fad3e2d8bb1f9a9f1",
          "sha1": "96fd89fe860c6dcbc164f3d722ed3d816779ca64",
          "md5": "12f205974710134416cdfacc1d2f99e2"
        }
      ]
    }
  ]
}
