{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "screen-recorder",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "screen-recorder-3.3.0.aar",
          "url": "screen-recorder-3.3.0.aar",
          "size": 70880,
          "sha512": "f28adeefe58b64a2ca1f64de78c2743b4caabadd0b8afe1767209d728bbf24e7e7e4468f02b9390c742b5e4f400876ab8c61892344cf186569be18632b59911c",
          "sha256": "f24b51c37d177e5ee8fa7fe68ebae6249fa7c606c4777b584e3cc283f88e59fa",
          "sha1": "1a481f51c17381069b14bcd185f4656a1f876cc4",
          "md5": "cef90d3eb066e4a7a61686be2ff8882a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "screen-recorder-3.3.0.aar",
          "url": "screen-recorder-3.3.0.aar",
          "size": 70880,
          "sha512": "f28adeefe58b64a2ca1f64de78c2743b4caabadd0b8afe1767209d728bbf24e7e7e4468f02b9390c742b5e4f400876ab8c61892344cf186569be18632b59911c",
          "sha256": "f24b51c37d177e5ee8fa7fe68ebae6249fa7c606c4777b584e3cc283f88e59fa",
          "sha1": "1a481f51c17381069b14bcd185f4656a1f876cc4",
          "md5": "cef90d3eb066e4a7a61686be2ff8882a"
        }
      ]
    }
  ]
}
