{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "recorder",
    "version": "2.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.2.aar",
          "url": "recorder-2.6.2.aar",
          "size": 128909,
          "sha512": "29eb47a43b37e00e3647b39bf479f333c75450700466829c5eefe637f409674f82086579104c3a0e946794c7f496aded4dcde8d7ea2043924487a2f1bd0d2e93",
          "sha256": "7f06234219735428af7c7d7cbe51b574737e176cebe6596439f1289d413046db",
          "sha1": "03dd9669f98ac13a5a4f78ec3e5661dad3cd4d9a",
          "md5": "11348759569c4a3353f4c79ba5bb6ade"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.46"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.2.aar",
          "url": "recorder-2.6.2.aar",
          "size": 128909,
          "sha512": "29eb47a43b37e00e3647b39bf479f333c75450700466829c5eefe637f409674f82086579104c3a0e946794c7f496aded4dcde8d7ea2043924487a2f1bd0d2e93",
          "sha256": "7f06234219735428af7c7d7cbe51b574737e176cebe6596439f1289d413046db",
          "sha1": "03dd9669f98ac13a5a4f78ec3e5661dad3cd4d9a",
          "md5": "11348759569c4a3353f4c79ba5bb6ade"
        }
      ]
    }
  ]
}
