{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "recorder",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.0.aar",
          "url": "recorder-2.6.0.aar",
          "size": 125484,
          "sha512": "4ae40d601358d92e9faa765dde91ac225c6195ca6f0a3d673058ca588d8c38c8297da88042505648385fbb57b7b30927522ae43df542d6d0b6e5956fbd599499",
          "sha256": "5bc359fa1f8ed8f7783728aa0995b074c26c8a1cf74dd2df2d2b7f381f3bf650",
          "sha1": "d117c19aba7c85f95b0d6a9a15df8419687cfef6",
          "md5": "91643f1af2da4ff2830f1490e8ec7dc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.46"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.0.aar",
          "url": "recorder-2.6.0.aar",
          "size": 125484,
          "sha512": "4ae40d601358d92e9faa765dde91ac225c6195ca6f0a3d673058ca588d8c38c8297da88042505648385fbb57b7b30927522ae43df542d6d0b6e5956fbd599499",
          "sha256": "5bc359fa1f8ed8f7783728aa0995b074c26c8a1cf74dd2df2d2b7f381f3bf650",
          "sha1": "d117c19aba7c85f95b0d6a9a15df8419687cfef6",
          "md5": "91643f1af2da4ff2830f1490e8ec7dc7"
        }
      ]
    }
  ]
}
