{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "recorder",
    "version": "2.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.4.aar",
          "url": "recorder-2.6.4.aar",
          "size": 129865,
          "sha512": "1854e4993d926987ab5bafb482f3933e53a556113d28b18c6ac6c0afa747eeb1d8b6efc89c025caaf1dcdf946ce45b1b9745e1731d02e2056529e9c06d78f8eb",
          "sha256": "75fb3d319f99b277ce91af163714b0dd1b2ba991d87a3c702e9450701e70997a",
          "sha1": "01a10ed4c6026a773c4ebc5bd123cedbf00caec9",
          "md5": "393aa89a3e7fc43c82831311bdb6dcbf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.63"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.4.aar",
          "url": "recorder-2.6.4.aar",
          "size": 129865,
          "sha512": "1854e4993d926987ab5bafb482f3933e53a556113d28b18c6ac6c0afa747eeb1d8b6efc89c025caaf1dcdf946ce45b1b9745e1731d02e2056529e9c06d78f8eb",
          "sha256": "75fb3d319f99b277ce91af163714b0dd1b2ba991d87a3c702e9450701e70997a",
          "sha1": "01a10ed4c6026a773c4ebc5bd123cedbf00caec9",
          "md5": "393aa89a3e7fc43c82831311bdb6dcbf"
        }
      ]
    }
  ]
}
