{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "recorder",
    "version": "2.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.5.aar",
          "url": "recorder-2.6.5.aar",
          "size": 130297,
          "sha512": "fded7e770f490586ded82815bcc5cdc9156701df7b4a33111a92e9a4465b44974e66f71473c77a6a92061204729c2de361d350eb1a1e244766dfb9aa1f492aba",
          "sha256": "03f33eac6b670b9b63815d05850cd1dfa5d5f5cc624e6de51bf1a44ee94eb985",
          "sha1": "103533049085eaf663927323cb589225e3fc24b0",
          "md5": "390b1293f8f70ca326208155c9c36832"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.71"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.5.aar",
          "url": "recorder-2.6.5.aar",
          "size": 130297,
          "sha512": "fded7e770f490586ded82815bcc5cdc9156701df7b4a33111a92e9a4465b44974e66f71473c77a6a92061204729c2de361d350eb1a1e244766dfb9aa1f492aba",
          "sha256": "03f33eac6b670b9b63815d05850cd1dfa5d5f5cc624e6de51bf1a44ee94eb985",
          "sha1": "103533049085eaf663927323cb589225e3fc24b0",
          "md5": "390b1293f8f70ca326208155c9c36832"
        }
      ]
    }
  ]
}
