{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "recorder",
    "version": "2.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.3.aar",
          "url": "recorder-2.6.3.aar",
          "size": 130452,
          "sha512": "7a271937571880bcef64a421a7d235c5ac92c3b8e2e940bb45daac64b04fd67e331857b771c00917950acd6838cfc0b785c97c5e288173e730a3f79a4dd6bcbd",
          "sha256": "6d5c4a3b6f51d207f7391b8e1eb9d881121aca5bd37ffed4c1c719e98b177fc0",
          "sha1": "e9a32f49a2a4aa1f741bf65ab4bfc3cdfd9ba112",
          "md5": "8a4243314a00c0ad464d21d012b76703"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk",
          "version": {
            "requires": "2.6.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.46"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "recorder-2.6.3.aar",
          "url": "recorder-2.6.3.aar",
          "size": 130452,
          "sha512": "7a271937571880bcef64a421a7d235c5ac92c3b8e2e940bb45daac64b04fd67e331857b771c00917950acd6838cfc0b785c97c5e288173e730a3f79a4dd6bcbd",
          "sha256": "6d5c4a3b6f51d207f7391b8e1eb9d881121aca5bd37ffed4c1c719e98b177fc0",
          "sha1": "e9a32f49a2a4aa1f741bf65ab4bfc3cdfd9ba112",
          "md5": "8a4243314a00c0ad464d21d012b76703"
        }
      ]
    }
  ]
}
